# ============================================================
# DRINK DATABASE - MÁY BÁN NƯỚC TỰ ĐỘNG
# ============================================================

DRINKS_DB = {
    "coca": {
        "name": "Coca-Cola",
        "aliases": ["coca", "coca cola", "coke", "coca-cola"],
        "brand": "Coca-Cola Company",
        "volumes": ["330ml", "500ml", "1.5L"],
        "default_volume": "330ml",
        "price": {"330ml": 12000, "500ml": 15000, "1.5L": 28000},
        "ingredients": "Nước, đường, CO2, màu caramel, acid phosphoric, hương liệu tự nhiên, caffeine",
        "flavor": "Vị ngọt đặc trưng, có ga, hương caramel nhẹ",
        "features": "Nước ngọt có ga kinh điển, giải khát tốt",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 9.5,
        "sales": 1500,
        "stock": 120,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🥤",
    },
    "pepsi": {
        "name": "Pepsi",
        "aliases": ["pepsi"],
        "brand": "PepsiCo",
        "volumes": ["330ml", "500ml", "1.5L"],
        "default_volume": "330ml",
        "price": {"330ml": 11000, "500ml": 14000, "1.5L": 26000},
        "ingredients": "Nước, đường, CO2, acid phosphoric, màu caramel, hương liệu, caffeine",
        "flavor": "Vị ngọt nhẹ hơn Coca, có ga, hương vanilla thoảng nhẹ",
        "features": "Nước ngọt có ga phổ biến toàn cầu",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 9.0,
        "sales": 1300,
        "stock": 100,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🥤",
    },
    "sting": {
        "name": "Sting",
        "aliases": ["sting", "nước tăng lực sting"],
        "brand": "PepsiCo",
        "volumes": ["330ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000},
        "ingredients": "Nước, đường, acid citric, taurine, caffeine, vitamin B3, B6, B12, hương dâu",
        "flavor": "Vị ngọt, hương dâu đặc trưng",
        "features": "Nước tăng lực phổ biến, giá rẻ, bổ sung năng lượng nhanh",
        "category": "Nước tăng lực",
        "is_new": False,
        "popularity": 8.8,
        "sales": 200,
        "stock": 150,
        "expiry_months": 11,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "⚡",
    },
    "redbull": {
        "name": "Red Bull",
        "aliases": ["redbull", "red bull", "bò húc"],
        "brand": "Red Bull GmbH",
        "volumes": ["250ml"],
        "default_volume": "250ml",
        "price": {"250ml": 18000},
        "ingredients": "Nước, đường, acid citric, taurine (1000mg), caffeine (80mg), niacinamide, vitamin B6, B12, pantothenate",
        "flavor": "Vị ngọt thanh, hơi chua nhẹ, có ga",
        "features": "Nước tăng lực cao cấp nhập khẩu, tăng sự tập trung và thể lực",
        "category": "Nước tăng lực",
        "is_new": False,
        "popularity": 9.2,
        "sales": 900,
        "stock": 80,
        "expiry_months": 18,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🐂",
    },
    "sprite": {
        "name": "Sprite",
        "aliases": ["sprite", "7 up sprite"],
        "brand": "Coca-Cola Company",
        "volumes": ["330ml", "500ml"],
        "default_volume": "330ml",
        "price": {"330ml": 11000, "500ml": 14000},
        "ingredients": "Nước, đường, CO2, acid citric, hương chanh tự nhiên",
        "flavor": "Vị chua ngọt, hương chanh tươi mát, có ga",
        "features": "Nước ngọt có ga không màu, giải khát mùa hè",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 8.5,
        "sales": 1000,
        "stock": 90,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍋",
    },
    "7up": {
        "name": "7UP",
        "aliases": ["7up", "7 up", "seven up"],
        "brand": "PepsiCo",
        "volumes": ["330ml", "500ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000, "500ml": 13000},
        "ingredients": "Nước, đường, CO2, acid citric, hương chanh & chanh xanh",
        "flavor": "Vị chua ngọt nhẹ, hương chanh xanh, có ga",
        "features": "Nước ngọt có ga trong suốt, thanh mát",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 8.0,
        "sales": 800,
        "stock": 70,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍋",
    },
    "fanta": {
        "name": "Fanta",
        "aliases": ["fanta", "fanta cam", "fanta nho"],
        "brand": "Coca-Cola Company",
        "volumes": ["330ml", "500ml"],
        "default_volume": "330ml",
        "price": {"330ml": 11000, "500ml": 14000},
        "ingredients": "Nước, đường, CO2, acid citric, hương cam/nho tự nhiên, màu thực phẩm",
        "flavor": "Vị ngọt đậm, hương trái cây (cam hoặc nho), có ga",
        "features": "Nước ngọt có ga hương trái cây, nhiều vị đa dạng",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 8.2,
        "sales": 850,
        "stock": 85,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍊",
    },
    "mirinda": {
        "name": "Mirinda",
        "aliases": ["mirinda", "mirinda cam"],
        "brand": "PepsiCo",
        "volumes": ["330ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000},
        "ingredients": "Nước, đường, CO2, acid citric, hương cam, màu thực phẩm",
        "flavor": "Vị ngọt đậm đà, hương cam nổi bật, có ga",
        "features": "Nước ngọt có ga hương cam đặc trưng",
        "category": "Nước ngọt có ga",
        "is_new": False,
        "popularity": 7.5,
        "sales": 600,
        "stock": 60,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍊",
    },
    "aquafina": {
        "name": "Aquafina",
        "aliases": ["aquafina", "nước suối aquafina"],
        "brand": "PepsiCo",
        "volumes": ["500ml", "1.5L"],
        "default_volume": "500ml",
        "price": {"500ml": 7000, "1.5L": 12000},
        "ingredients": "Nước tinh khiết (qua lọc RO 7 bước)",
        "flavor": "Vị thanh khiết, không mùi không vị",
        "features": "Nước tinh khiết đóng chai, lọc 7 bước RO",
        "category": "Nước suối / tinh khiết",
        "is_new": False,
        "popularity": 8.8,
        "sales": 1100,
        "stock": 200,
        "expiry_months": 24,
        "has_sugar": False,
        "has_caffeine": False,
        "image": "💧",
    },
    "lavie": {
        "name": "La Vie",
        "aliases": ["lavie", "la vie", "nước suối lavie"],
        "brand": "Nestlé",
        "volumes": ["500ml", "1.5L"],
        "default_volume": "500ml",
        "price": {"500ml": 8000, "1.5L": 13000},
        "ingredients": "Nước khoáng thiên nhiên, khoáng chất tự nhiên (Ca, Mg, Na...)",
        "flavor": "Vị thanh nhẹ, chứa khoáng chất tự nhiên",
        "features": "Nước khoáng thiên nhiên, bổ sung khoáng chất cho cơ thể",
        "category": "Nước khoáng",
        "is_new": False,
        "popularity": 8.5,
        "sales": 950,
        "stock": 180,
        "expiry_months": 24,
        "has_sugar": False,
        "has_caffeine": False,
        "image": "💧",
    },
    "revive": {
        "name": "Revive",
        "aliases": ["revive", "nước điện giải revive"],
        "brand": "Coca-Cola Company",
        "volumes": ["500ml"],
        "default_volume": "500ml",
        "price": {"500ml": 10000},
        "ingredients": "Nước, đường, muối, kali citrate, natri citrate, kẽm gluconate, vitamin C, hương chanh muối",
        "flavor": "Vị mặn ngọt nhẹ, hương chanh muối đặc trưng",
        "features": "Nước điện giải bù khoáng, tốt sau khi vận động hoặc bị mất nước",
        "category": "Nước điện giải",
        "is_new": False,
        "popularity": 8.3,
        "sales": 700,
        "stock": 90,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "⚗️",
    },
    "c2": {
        "name": "C2",
        "aliases": ["c2", "trà xanh c2", "c2 hương chanh"],
        "brand": "URC Việt Nam",
        "volumes": ["360ml", "455ml"],
        "default_volume": "360ml",
        "price": {"360ml": 9000, "455ml": 11000},
        "ingredients": "Nước, đường, chiết xuất trà xanh, acid citric, hương chanh, vitamin C",
        "flavor": "Vị ngọt nhẹ, hương trà xanh và chanh tươi mát",
        "features": "Trà xanh đóng chai phổ biến, chứa chất chống oxy hóa từ trà xanh",
        "category": "Trà đóng chai",
        "is_new": False,
        "popularity": 8.7,
        "sales": 1050,
        "stock": 110,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🍵",
    },
    "tra_xanh_khong_do": {
        "name": "Trà Xanh Không Độ",
        "aliases": ["trà xanh không độ", "tra xanh khong do", "không độ"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["350ml", "500ml"],
        "default_volume": "350ml",
        "price": {"350ml": 9000, "500ml": 12000},
        "ingredients": "Nước, chiết xuất trà xanh, đường, acid citric, hương jasmine",
        "flavor": "Vị trà nhẹ, hương hoa nhài thoảng, ít ngọt",
        "features": "Trà xanh thuần Việt, ít calo, giải khát tự nhiên",
        "category": "Trà đóng chai",
        "is_new": False,
        "popularity": 8.6,
        "sales": 980,
        "stock": 100,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🍵",
    },
    "olong_tea": {
        "name": "Olong Tea+",
        "aliases": ["olong tea", "olong tea plus", "trà ô long", "olong"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["350ml"],
        "default_volume": "350ml",
        "price": {"350ml": 9000},
        "ingredients": "Nước, chiết xuất trà ô long, đường thấp, hương trà tự nhiên",
        "flavor": "Vị trà đậm, hương ô long đặc trưng, ít ngọt",
        "features": "Trà ô long ít đường, giúp giảm béo và tốt cho tiêu hóa",
        "category": "Trà đóng chai",
        "is_new": False,
        "popularity": 7.8,
        "sales": 650,
        "stock": 75,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🍵",
    },
    "dr_thanh": {
        "name": "Dr Thanh",
        "aliases": ["dr thanh", "dr. thanh", "nước thảo mộc dr thanh"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["350ml"],
        "default_volume": "350ml",
        "price": {"350ml": 10000},
        "ingredients": "Nước, chiết xuất 9 loại thảo mộc (la hán quả, kim ngân hoa, hoa cúc...), đường, acid citric",
        "flavor": "Vị ngọt thanh, hương thảo mộc nhẹ, hơi đắng nhẹ đặc trưng",
        "features": "Nước thảo mộc thanh nhiệt, giải độc, tốt cho sức khỏe",
        "category": "Nước thảo mộc",
        "is_new": False,
        "popularity": 8.0,
        "sales": 720,
        "stock": 80,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🌿",
    },
    "monster": {
        "name": "Monster Energy",
        "aliases": ["monster", "monster energy", "quái vật"],
        "brand": "Monster Beverage Corporation",
        "volumes": ["355ml", "500ml"],
        "default_volume": "355ml",
        "price": {"355ml": 25000, "500ml": 35000},
        "ingredients": "Nước, đường, CO2, taurine, ginseng extract, L-carnitine, caffeine (160mg/500ml), vitamin B, niacin",
        "flavor": "Vị ngọt mạnh, có ga, hương trái cây hỗn hợp",
        "features": "Nước tăng lực cao cấp nhập khẩu, caffeine cao, phù hợp gymer và gamer",
        "category": "Nước tăng lực",
        "is_new": False,
        "popularity": 8.9,
        "sales": 560,
        "stock": 60,
        "expiry_months": 24,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "👾",
    },
    "number1": {
        "name": "Number 1",
        "aliases": ["number 1", "số 1", "nước tăng lực số 1", "nước tăng lực number 1"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["330ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000},
        "ingredients": "Nước, đường, taurine, inositol, caffeine, vitamin B3, B6, B12",
        "flavor": "Vị ngọt, hương sâm nhẹ",
        "features": "Nước tăng lực Việt, giá tốt, phù hợp mọi đối tượng",
        "category": "Nước tăng lực",
        "is_new": False,
        "popularity": 7.5,
        "sales": 700,
        "stock": 100,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "⚡",
    },
    "warrior": {
        "name": "Warrior",
        "aliases": ["warrior", "chiến binh"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["330ml"],
        "default_volume": "330ml",
        "price": {"330ml": 9000},
        "ingredients": "Nước, đường, taurine (800mg), caffeine, vitamin B6, vitamin B12, niacin, acid citric",
        "flavor": "Vị ngọt, nhẹ ga, hương trái cây",
        "features": "Nước tăng lực giá rẻ, phù hợp học sinh sinh viên",
        "category": "Nước tăng lực",
        "is_new": False,
        "popularity": 7.0,
        "sales": 580,
        "stock": 90,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "⚡",
    },
    "yakult": {
        "name": "Yakult",
        "aliases": ["yakult", "sữa chua uống yakult"],
        "brand": "Yakult Honsha",
        "volumes": ["65ml"],
        "default_volume": "65ml",
        "price": {"65ml": 8000},
        "ingredients": "Nước, sữa gầy, đường, men vi sinh Lactobacillus casei Shirota (6.5 tỷ vi khuẩn/chai)",
        "flavor": "Vị chua ngọt đặc trưng, thơm sữa",
        "features": "Sữa chua uống men vi sinh, tốt cho tiêu hóa và hệ miễn dịch",
        "category": "Sữa chua uống",
        "is_new": False,
        "popularity": 8.4,
        "sales": 800,
        "stock": 120,
        "expiry_months": 1,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍶",
    },
    "vinamilk_socola": {
        "name": "Vinamilk Sô-cô-la",
        "aliases": ["vinamilk socola", "sữa vinamilk socola", "vinamilk có socola", "vinamilk"],
        "brand": "Vinamilk",
        "volumes": ["180ml", "250ml"],
        "default_volume": "180ml",
        "price": {"180ml": 8000, "250ml": 12000},
        "ingredients": "Sữa tươi, đường, bột cacao, hương vani",
        "flavor": "Vị ngọt, béo thơm, hương socola đậm đà",
        "features": "Sữa tươi tiệt trùng hương socola, giàu canxi và protein",
        "category": "Sữa",
        "is_new": False,
        "popularity": 8.0,
        "sales": 650,
        "stock": 85,
        "expiry_months": 6,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍫",
    },
    "th_true_milk": {
        "name": "TH True Milk",
        "aliases": ["th true milk", "th milk", "sữa th"],
        "brand": "TH Group",
        "volumes": ["180ml", "500ml", "1L"],
        "default_volume": "180ml",
        "price": {"180ml": 9000, "500ml": 18000, "1L": 32000},
        "ingredients": "Sữa tươi nguyên chất 100%, vitamin A, D, B2, canxi",
        "flavor": "Vị ngọt thanh, béo nhẹ, thơm mùi sữa tự nhiên",
        "features": "Sữa tươi nguyên chất 100%, không chất bảo quản, từ trang trại sạch",
        "category": "Sữa",
        "is_new": False,
        "popularity": 8.7,
        "sales": 750,
        "stock": 80,
        "expiry_months": 1,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🥛",
    },
    "dutch_lady": {
        "name": "Dutch Lady",
        "aliases": ["dutch lady", "cô gái hà lan", "sữa dutch lady"],
        "brand": "FrieslandCampina",
        "volumes": ["180ml", "1L"],
        "default_volume": "180ml",
        "price": {"180ml": 8500, "1L": 30000},
        "ingredients": "Sữa tươi, đường, vitamin (A, D, B1, B2, B6, C), canxi, sắt",
        "flavor": "Vị ngọt vừa, thơm, béo nhẹ",
        "features": "Sữa tiệt trùng giàu dinh dưỡng, bổ sung vitamin và khoáng chất",
        "category": "Sữa",
        "is_new": False,
        "popularity": 8.1,
        "sales": 600,
        "stock": 70,
        "expiry_months": 6,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🥛",
    },
    "nescafe": {
        "name": "Nescafé Ready To Drink",
        "aliases": ["nescafe", "nescafé", "cafe nescafe", "nescafe lon"],
        "brand": "Nestlé",
        "volumes": ["180ml"],
        "default_volume": "180ml",
        "price": {"180ml": 15000},
        "ingredients": "Nước, đường, cà phê hòa tan (2%), sữa, hương cà phê tự nhiên",
        "flavor": "Vị đắng nhẹ, thơm cà phê, ngọt vừa",
        "features": "Cà phê uống liền tiện lợi, tỉnh táo nhanh",
        "category": "Cà phê đóng lon",
        "is_new": False,
        "popularity": 7.8,
        "sales": 480,
        "stock": 60,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "☕",
    },
    "birdy": {
        "name": "Café Birdy",
        "aliases": ["birdy", "cafe birdy", "birdy cà phê"],
        "brand": "Ajinomoto",
        "volumes": ["170ml"],
        "default_volume": "170ml",
        "price": {"170ml": 12000},
        "ingredients": "Nước, đường, cà phê Robusta, sữa đặc, hương cà phê",
        "flavor": "Vị đắng đậm đà, ngọt sữa, hương cà phê Robusta mạnh",
        "features": "Cà phê lon Thái Lan nổi tiếng, vị đậm đà đặc trưng",
        "category": "Cà phê đóng lon",
        "is_new": False,
        "popularity": 7.5,
        "sales": 400,
        "stock": 50,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "☕",
    },
    "lipton": {
        "name": "Lipton Trà Đào",
        "aliases": ["lipton", "trà lipton", "lipton đào", "lipton trà xanh"],
        "brand": "Unilever",
        "volumes": ["330ml", "455ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000, "455ml": 13000},
        "ingredients": "Nước, đường, chiết xuất trà, acid citric, hương đào tự nhiên, vitamin C",
        "flavor": "Vị ngọt nhẹ, hương đào thơm tươi mát",
        "features": "Trà đào đóng chai, thanh mát, ít calo hơn nước ngọt",
        "category": "Trà đóng chai",
        "is_new": False,
        "popularity": 7.9,
        "sales": 680,
        "stock": 80,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🍑",
    },
    "nestea": {
        "name": "Nestea Trà Đào",
        "aliases": ["nestea", "nestea đào", "trà nestea"],
        "brand": "Nestlé",
        "volumes": ["330ml"],
        "default_volume": "330ml",
        "price": {"330ml": 10000},
        "ingredients": "Nước, đường, chiết xuất trà, hương đào, acid citric, vitamin C",
        "flavor": "Vị chua ngọt, hương đào đậm hơn Lipton",
        "features": "Trà đào đóng lon, giải khát tốt",
        "category": "Trà đóng chai",
        "is_new": False,
        "popularity": 7.6,
        "sales": 550,
        "stock": 65,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "🍑",
    },
    "cocoxim": {
        "name": "Cocoxim Nước Dừa",
        "aliases": ["cocoxim", "nước dừa cocoxim", "cocoxim dừa"],
        "brand": "Cocoxim",
        "volumes": ["330ml", "1L"],
        "default_volume": "330ml",
        "price": {"330ml": 15000, "1L": 38000},
        "ingredients": "Nước dừa tươi nguyên chất (100%), không thêm đường, không chất bảo quản",
        "flavor": "Vị ngọt nhẹ tự nhiên, thanh mát đặc trưng của dừa tươi",
        "features": "Nước dừa nguyên chất, giàu điện giải tự nhiên, không đường thêm vào",
        "category": "Nước trái cây / dừa",
        "is_new": False,
        "popularity": 8.3,
        "sales": 620,
        "stock": 70,
        "expiry_months": 12,
        "has_sugar": False,
        "has_caffeine": False,
        "image": "🥥",
    },
    "twister": {
        "name": "Twister Nước Cam",
        "aliases": ["twister", "nước cam twister", "twister cam"],
        "brand": "Coca-Cola Company",
        "volumes": ["455ml"],
        "default_volume": "455ml",
        "price": {"455ml": 12000},
        "ingredients": "Nước cam ép (15%), nước, đường, acid citric, vitamin C, hương cam tự nhiên",
        "flavor": "Vị chua ngọt, hương cam tươi",
        "features": "Nước cam ép phổ biến, bổ sung vitamin C",
        "category": "Nước trái cây",
        "is_new": False,
        "popularity": 7.7,
        "sales": 500,
        "stock": 60,
        "expiry_months": 9,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🍊",
    },
    "aloe_vera": {
        "name": "Aloe Vera Nha Đam",
        "aliases": ["aloe vera", "nha đam", "nước nha đam", "aloe"],
        "brand": "Woongjin",
        "volumes": ["500ml"],
        "default_volume": "500ml",
        "price": {"500ml": 18000},
        "ingredients": "Nước, đường, thịt nha đam (8%), acid citric, vitamin C, hương nha đam",
        "flavor": "Vị ngọt nhẹ, thanh mát, có thịt nha đam giòn giòn",
        "features": "Nước nha đam Hàn Quốc, tốt cho da và tiêu hóa",
        "category": "Nước trái cây / thảo mộc",
        "is_new": True,
        "popularity": 8.1,
        "sales": 430,
        "stock": 55,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🌵",
    },
    "wake_up_247": {
        "name": "Wake Up 247",
        "aliases": ["wake up", "wake up 247", "cà phê wake up"],
        "brand": "Tân Hiệp Phát",
        "volumes": ["240ml"],
        "default_volume": "240ml",
        "price": {"240ml": 13000},
        "ingredients": "Nước, cà phê rang xay (Robusta & Arabica), đường, sữa, hương cà phê",
        "flavor": "Vị đắng đậm, thơm cà phê rang, ngọt vừa",
        "features": "Cà phê lon Việt, vị đậm đà, giá tốt",
        "category": "Cà phê đóng lon",
        "is_new": False,
        "popularity": 7.6,
        "sales": 450,
        "stock": 55,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": True,
        "image": "☕",
    },
    "tra_gao_rut": {
        "name": "Trà Gạo Lứt Rang",
        "aliases": ["trà gạo lứt", "trà gạo rang", "gạo lứt"],
        "brand": "Fami",
        "volumes": ["350ml"],
        "default_volume": "350ml",
        "price": {"350ml": 10000},
        "ingredients": "Nước, gạo lứt rang, đường thốt nốt, muối tinh, hương gạo tự nhiên",
        "flavor": "Vị bùi thơm của gạo rang, ngọt nhẹ, hương quê đặc trưng",
        "features": "Trà gạo lứt thuần Việt, tốt cho người ăn kiêng và người tiểu đường",
        "category": "Trà thảo mộc",
        "is_new": True,
        "popularity": 7.2,
        "sales": 280,
        "stock": 40,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🌾",
    },
    "vita_milk": {
        "name": "Vita Milk Sữa Đậu Nành",
        "aliases": ["vita milk", "vitamilk", "sữa đậu nành vita", "sữa đậu nành"],
        "brand": "Vita Food",
        "volumes": ["200ml"],
        "default_volume": "200ml",
        "price": {"200ml": 9000},
        "ingredients": "Nước, đậu nành (20%), đường, muối, vitamin D, canxi",
        "flavor": "Vị ngọt béo đặc trưng của đậu nành, thơm nhẹ",
        "features": "Sữa đậu nành Thái Lan nổi tiếng, giàu protein thực vật",
        "category": "Sữa thực vật",
        "is_new": False,
        "popularity": 7.9,
        "sales": 520,
        "stock": 65,
        "expiry_months": 12,
        "has_sugar": True,
        "has_caffeine": False,
        "image": "🫘",
    },
}

# ============================================================
# LOOKUP FUNCTION - Tìm sản phẩm theo tên/alias
# ============================================================

def find_drink(name: str):
    """Tìm drink theo tên hoặc alias, trả về (key, drink_data) hoặc (None, None)"""
    name_lower = name.lower().strip()
    for key, drink in DRINKS_DB.items():
        if name_lower == key:
            return key, drink
        for alias in drink["aliases"]:
            if alias in name_lower or name_lower in alias:
                return key, drink
    return None, None

def get_menu_list():
    """Trả về danh sách tên thức uống kèm giá cơ bản"""
    categories = {}
    for key, drink in DRINKS_DB.items():
        cat = drink["category"]
        if cat not in categories:
            categories[cat] = []
        default_vol = drink["default_volume"]
        price = drink["price"][default_vol]
        categories[cat].append(f"{drink['name']} ({default_vol}) - {price:,}đ")
    return categories

def get_recommendations():
    """Top 5 sản phẩm bán chạy và phổ biến nhất"""
    sorted_drinks = sorted(DRINKS_DB.items(), key=lambda x: x[1]["popularity"], reverse=True)
    return [(k, v) for k, v in sorted_drinks[:5]]

def get_new_products():
    """Sản phẩm mới"""
    return [(k, v) for k, v in DRINKS_DB.items() if v["is_new"]]
